basePath: /api
definitions:
  model.Film:
    properties:
      actors:
        description: Diễn viên (mảng chuỗi)
        items:
          type: string
        type: array
      created_at:
        description: Ngày tạo
        type: string
      description:
        description: Mô tả
        type: string
      director:
        description: Đạo diễn
        type: string
      duration:
        description: Thời lượng
        type: integer
      end_date:
        description: Ngày kết thúc (có thể null)
        type: string
      genre:
        description: Thể loại (mảng chuỗi)
        items:
          type: string
        type: array
      id:
        description: ID duy nhất của phim
        type: integer
      is_coming_soon:
        description: Sắp chiếu?
        type: boolean
      is_now_showing:
        description: Đang chiếu?
        type: boolean
      poster_url:
        description: Link poster
        type: string
      rated:
        description: Phân loại độ tuổi
        type: string
      rating_avg:
        description: Điểm TB
        type: number
      rating_count:
        description: Số lượt đánh giá
        type: integer
      release_date:
        description: Ngày khởi chiếu
        type: string
      title:
        description: Tên phim
        type: string
      trailer_url:
        description: Link trailer
        type: string
      updated_at:
        description: Ngày cập nhật
        type: string
    type: object
  model.Response:
    properties:
      data: {}
      message:
        type: string
      statusCode:
        type: integer
    type: object
  model.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      fullName:
        type: string
      password:
        type: string
      role:
        type: string
      token:
        description: Thêm cột token vào đây
        type: string
      updatedAt:
        type: string
    type: object
  req.FilmReq:
    properties:
      actors:
        description: Danh sách diễn viên
        items:
          type: string
        minItems: 1
        type: array
      description:
        description: Mô tả nội dung
        type: string
      director:
        description: Tên đạo diễn
        type: string
      duration:
        description: Thời lượng (>=1 phút)
        minimum: 1
        type: integer
      end_date:
        description: Ngày kết thúc chiếu (có thể null)
        type: string
      genre:
        description: Thể loại phim
        items:
          type: string
        minItems: 1
        type: array
      is_coming_soon:
        description: Sắp chiếu hay không
        type: boolean
      is_now_showing:
        description: Đang chiếu hay không
        type: boolean
      poster_url:
        description: Link ảnh poster
        type: string
      rated:
        description: Phân loại độ tuổi
        type: string
      release_date:
        description: Ngày khởi chiếu
        type: string
      title:
        description: Tên phim (bắt buộc)
        type: string
      trailer_url:
        description: Link trailer
        type: string
    required:
    - actors
    - description
    - director
    - duration
    - genre
    - poster_url
    - rated
    - release_date
    - title
    - trailer_url
    type: object
  req.ReqSignIn:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  req.ReqSignUp:
    properties:
      email:
        type: string
      fullName:
        description: tags
        type: string
      password:
        type: string
    required:
    - email
    - fullName
    - password
    type: object
host: localhost:3000
info:
  contact: {}
  description: A Tag service API in Go using Gin framework
  title: Tag Service API
  version: "1.0"
paths:
  /admin/add-film:
    post:
      consumes:
      - application/json
      description: Chỉ admin mới có quyền thêm phim mới vào hệ thống
      parameters:
      - description: Token (Bearer {token})
        in: header
        name: Authorization
        required: true
        type: string
      - description: Thông tin phim cần lưu
        in: body
        name: film
        required: true
        schema:
          $ref: '#/definitions/req.FilmReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Film'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  items:
                    type: string
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.Response'
        "415":
          description: Unsupported Media Type
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - BearerAuth: []
      summary: Thêm phim mới
      tags:
      - film
  /admin/delete-film/{id}:
    delete:
      consumes:
      - application/json
      description: Chỉ admin mới có quyền thêm phim mới vào hệ thống
      parameters:
      - description: Token (Bearer {token})
        in: header
        name: Authorization
        required: true
        type: string
      - description: Film ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Film'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - BearerAuth: []
      summary: delete a film
      tags:
      - film
  /film/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Film ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Film'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Show an film
      tags:
      - film
  /films:
    get:
      consumes:
      - application/json
      description: Trả về danh sách tất cả phim có trong hệ thống
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Film'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Lấy danh sách tất cả phim
      tags:
      - film
  /user/sign-in:
    post:
      consumes:
      - application/json
      description: API cho phép người dùng đăng nhập và nhận token
      parameters:
      - description: Thông tin đăng nhập
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/req.ReqSignIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  additionalProperties: true
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Đăng nhập
      tags:
      - user
  /user/sign-up:
    post:
      consumes:
      - application/json
      description: API cho phép người dùng đăng ký tài khoản mới
      parameters:
      - description: Thông tin đăng ký
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/req.ReqSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: Đăng ký tài khoản mới
      tags:
      - user
swagger: "2.0"
